# Config for running the InferenceRecipe in generate.py to generate output from an LLM
#
# To launch, run the following command from root torchtune directory:
#    tune run generate --config generation

# Model arguments
model:
  _component_: torchtune.models.llama3_1.lora_llama3_1_8b

representation_type: zmatrix 

generation:
  n_structures: 5
  batch_size: 1 # no batch inference yet; this is a placeholder 
  output_dir: exp/outputs

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: exp/lora-zmatrix-llama3_1/
  checkpoint_files: [
    hf_model_0001_9.pt,
    hf_model_0002_9.pt,
    hf_model_0003_9.pt,
    hf_model_0004_9.pt
  ]
  output_dir: exp/outputs
  model_type: LLAMA3

device: cuda
dtype: bf16

seed: 

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /tmp/Meta-Llama-3.1-8B/original/tokenizer.model


# Generation arguments; defaults taken from gpt-fast
prompt: null
instruct_template: null
chat_format: null
max_new_tokens: 1024
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300
# It is recommended to set enable_kv_cache=False for long-context models like Llama3.1
enable_kv_cache: True

quantizer: null
